export enum Routes {
  Default = "/",
  NodeCreation = "/node-creation",
  About = "/about",
  Save = "/save",
  Load = "/load",
  ExportGif = "/export-gif",
  CustomFunction = "/custom-function",
  CustomShader = "/custom-shader",
  CustomSimulation = "/custom-simulation",
  Settings = "/settings",
  Paint = "/paint",
  CodeBlock = "/code_block",
  SketchMenu = "/sketch_menu",
  JavascriptFunction = "/js_function",
}
